Repository codestates-seb/seb45_pre_021, pull requests merged in 2023-08, with the labels that each got.

#9 ✨ feat: 데이터 저장 일자, 시간 기록 자동화
  server/src/main/java/com/teamtwentyone/BackendServerApplication.java
  server/src/main/java/com/teamtwentyone/time/DateTimeEntity.java
  server/src/main/java/com/teamtwentyone/time/UserDateEntity.java
  server/src/main/java/com/teamtwentyone/users/Dto/UserDto.java
  server/src/main/java/com/teamtwentyone/users/controller/UserController.java
  server/src/main/java/com/teamtwentyone/users/entity/User.java
  server/src/main/java/com/teamtwentyone/users/mapper/UserMapper.java
  server/src/main/java/com/teamtwentyone/users/repository/UserRepository.java
  server/src/main/java/com/teamtwentyone/users/service/UserService.java
Labels: ✨ 기능 추가

#16 🐛 fix: eslint의 Delete 'cs' prettier/prettier 문제 해결
  client/.eslintrc.json
Labels: 🐛 버그 수정

#18 ✨ feat: Footer 컴포넌트 작성
  client/src/components/Footer.jsx
  client/src/imgs/footer_logo.png
  client/src/imgs/footer_notion_icon.png
Labels: ✨ 기능 추가

#24 ✨ feat: 에러 처리 로직, User CRUD 구현
  server/src/main/java/com/teamtwentyone/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/teamtwentyone/exception/BusinessLogicException.java
  server/src/main/java/com/teamtwentyone/exception/ExceptionCode.java
  server/src/main/java/com/teamtwentyone/response/ErrorResponse.java
  server/src/main/java/com/teamtwentyone/users/Dto/UserDto.java
  server/src/main/java/com/teamtwentyone/users/controller/UserController.java
  server/src/main/java/com/teamtwentyone/users/entity/User.java
  server/src/main/java/com/teamtwentyone/users/repository/UserRepository.java
  server/src/main/java/com/teamtwentyone/users/service/UserService.java
Labels: ✨ 기능 추가

#29 ✨ feat: Sidebar 컴포넌트 작성
  client/src/components/Sidebar.jsx
Labels: ✨ 기능 추가

#31 ✨ feat: 질문 글 작성 페이지
  client/package-lock.json
  client/package.json
  client/src/components/Editor.jsx
  client/src/components/Viewer.jsx
  client/src/components/post/Card.jsx
  client/src/components/post/DetailSection.jsx
  client/src/components/post/NextButton.jsx
  client/src/components/post/NoticeSection.jsx
  client/src/components/post/TitleSection.jsx
  client/src/imgs/post_card_icon.png
  client/src/imgs/post_kana.png
  client/src/pages/questions/Post.jsx
Labels: ✨ 기능 추가

#32 ✨ feat: Login 페이지 구현
  client/src/imgs/google_icon.svg
  client/src/pages/users/Login.jsx
Labels: ✨ 기능 추가

#33 ✨ feat: 메인 페이지 (팀 소개 및 기술 스택)
  client/src/components/ProfileIcon.jsx
  client/src/imgs/profile-img.jpeg
  client/src/pages/Home.jsx
Labels: ✨ 기능 추가

#43 ✨feat: api 전체 기능 구현 v1
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/backend-server.main.iml
  .idea/seb45_pre_021-test.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  server/src/main/java/com/teamtwentyone/answers/controller/AnswerController.java
  server/src/main/java/com/teamtwentyone/answers/dto/AnswerDto.java
  server/src/main/java/com/teamtwentyone/answers/entity/Answer.java
  server/src/main/java/com/teamtwentyone/answers/mapper/AnswerMapper.java
  server/src/main/java/com/teamtwentyone/answers/repository/AnswerRepository.java
  server/src/main/java/com/teamtwentyone/answers/service/AnswerService.java
  server/src/main/java/com/teamtwentyone/auth/config/SecurityConfig.java
  server/src/main/java/com/teamtwentyone/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/teamtwentyone/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/teamtwentyone/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/teamtwentyone/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/teamtwentyone/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/teamtwentyone/auth/userdetails/MemberUserDetailService.java
  server/src/main/java/com/teamtwentyone/auth/utils/ErrorResponseSender.java
  server/src/main/java/com/teamtwentyone/dto/MultiResponseDto.java
  server/src/main/java/com/teamtwentyone/dto/PageInfo.java
  server/src/main/java/com/teamtwentyone/exception/BusinessLogicException.java
  server/src/main/java/com/teamtwentyone/exception/ExceptionCode.java
  server/src/main/java/com/teamtwentyone/questions/controller/QuestionsController.java
  server/src/main/java/com/teamtwentyone/questions/dto/QuestionsDto.java
  server/src/main/java/com/teamtwentyone/questions/entity/Question.java
  server/src/main/java/com/teamtwentyone/questions/mapper/QuestionsMapper.java
  server/src/main/java/com/teamtwentyone/questions/repository/QuestionsRepository.java
  server/src/main/java/com/teamtwentyone/questions/service/QuestionsService.java
  server/src/main/java/com/teamtwentyone/response/ErrorResponse.java
  server/src/main/java/com/teamtwentyone/time/DateTimeEntity.java
  server/src/main/java/com/teamtwentyone/time/UserDateEntity.java
  server/src/main/java/com/teamtwentyone/users/Dto/UserDto.java
  server/src/main/java/com/teamtwentyone/users/controller/UserController.java
  server/src/main/java/com/teamtwentyone/users/entity/User.java
  server/src/main/java/com/teamtwentyone/users/mapper/UserMapper.java
  server/src/main/java/com/teamtwentyone/users/repository/UserRepository.java
  server/src/main/java/com/teamtwentyone/users/service/UserService.java
  server/src/main/resources/application-local.yml
Labels: ✨ 기능 추가

#38 ✨ feat: 버튼 컴포넌트 수정
  client/src/components/Button.jsx
  client/src/components/post/NextButton.jsx
  client/src/components/post/TitleSection.jsx
  client/src/pages/questions/Post.jsx
Labels: 💄HTML/CSS, ✨ 기능 추가

#42 ✨ feat: NotFound 페이지 작성
  client/src/imgs/not_found.png
  client/src/pages/NotFound.jsx
Labels: ✨ 기능 추가

#45 ✨ feat: Questions 페이지 구현
  client/src/components/RightSidebar.jsx
  client/src/pages/questions/Main.jsx
Labels: ✨ 기능 추가

#50 ✨ feat: Sign up 페이지 유효성 검사 & 회원가입 로직 기능 추가
  client/src/pages/users/Register.jsx
Labels: ✨ 기능 추가, 🐛 버그 수정

#51 ✨ feat: Login 페이지 유효성 검사 & 로그인 로직 기능 추가
  client/src/pages/users/Login.jsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 🐛 버그 수정

#53 🥽 test: HeaderDropdown 컴포넌트 삭제
  client/src/components/HeaderDropdown.jsx
  client/src/components/Nav.jsx
  client/src/imgs/HeaderButton.svg
Labels: 💄HTML/CSS

#55 ✨ feat: 메인 배너 클릭 시, questions 페이지로 이동하는 기능 추가
  client/src/pages/Home.jsx
Labels: ✨ 기능 추가

#57 ✨ feat: 에러 발생 시, 팝업 창 띄우기 & 로그인 페이지로 이동하는 기능 추가
  client/src/pages/users/Register.jsx
Labels: ✨ 기능 추가

#58 ✨ feat: 로그인 시, 발급받은 토큰을 localStorage에 저장하는 로직 추가
  client/src/pages/users/Login.jsx
Labels: ✨ 기능 추가

#61 ✨ feat: 로그인 시, Nav 컴포넌트 변경
  client/src/App.js
  client/src/components/Nav.jsx
  client/src/pages/users/Login.jsx
Labels: ♻️ 리팩토링, ✨ 기능 추가

#62 ✨ feat: FE_마이페이지
  client/package-lock.json
  client/package.json
  client/src/components/ActivityBox.jsx
  client/src/components/MyPageBoxes.jsx
  client/src/components/ProfileBox.jsx
  client/src/components/SavesBox.jsx
  client/src/components/SettingBox.jsx
  client/src/pages/users/MyPage.jsx
Labels: ✨ 기능 추가

#63 FE_질문 전체 조회 페이지 추가 작업
  client/public/data/allQuestions.json
  client/src/components/RightSidebar.jsx
  client/src/pages/questions/Main.jsx
Labels: ♻️ 리팩토링, ⚙️ 설정, 💄HTML/CSS, ✨ 기능 추가

#69 FE_마이페이지 업데이트
  client/src/App.js
  client/src/components/Nav.jsx
  client/src/components/myPage/ActivityBox.jsx
  client/src/components/myPage/ProfileBox.jsx
  client/src/components/myPage/SavesBox.jsx
  client/src/components/myPage/SettingBox.jsx
  client/src/pages/users/MyPage.jsx
  client/src/utils/profiles.js
Labels: ♻️ 리팩토링, ✨ 기능 추가

#72 FE_질문 등록, 수정 페이지 업데이트
  client/src/pages/questions/Edit.jsx
  client/src/pages/questions/Post.jsx
Labels: ✨ 기능 추가

#74 FE_질문 검색 기능
  client/src/App.js
  client/src/components/Nav.jsx
  client/src/pages/Home.jsx
  client/src/pages/questions/Search.jsx
Labels: 💄HTML/CSS, ✨ 기능 추가

#75 ✨feat: Feat/question answer
  client/src/App.js
  client/src/components/Editor.jsx
  client/src/components/detail/AnswerSection.jsx
  client/src/pages/questions/Detail.jsx
  client/src/pages/questions/Main.jsx
Labels: ✨ 기능 추가
